version: 2

jobs:
  test:
    docker:
      - image: circleci/node:12.3.1
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ .Branch }}
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-cache-{{ .Branch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: yarn test

  publish:
    docker:
      - image: circleci/node:12.3.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Add npm token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Semantic release
          command: yarn release

workflows:
  version: 2
  test_and_publish:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only:
                - master
